### ISSUE TITLE
Error when creating classic instance 

### ISSUE THREAD

**Issue by lsh23** [NaverCloudPlatform/terraform-provider-ncloud#178]
### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : v1.0.9
Ncloud Provider version : v2.1.2
```

### Affected Resource(s)

* ncloud_server

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
terraform {
  required_version = ">= 0.13"
  required_providers {
    ncloud = {
      source  = "NaverCloudPlatform/ncloud"
    }
  }
}

provider "ncloud" {
  access_key  = var.access_key
  secret_key  = var.secret_key
  region      = "KR"
}

resource "ncloud_server" "test" {
    name                           = "test"
    server_product_code            = "SPSVRSTAND000004"
    server_image_product_code      = "SPSW0LINUX000139"
    zone                           = "KR-1"
}

resource "ncloud_server" "test2" {
    name                           = "test2"
    server_product_code            = "SPSVRSTAND000024"
    server_image_product_code      = "SPSW0LINUX000139"
    zone                           = "KR-1"
}

```

### Debug Output

```
Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ncloud_server.test: Creating...
ncloud_server.test2: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with ncloud_server.test,
│   on instance.tf line 52, in resource "ncloud_server" "test":
│   52: resource "ncloud_server" "test" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with ncloud_server.test2,
│   on instance.tf line 60, in resource "ncloud_server" "test2":
│   60: resource "ncloud_server" "test2" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-ncloud_v2.1.2 plugin:
```

### Panic Output

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b4b960]

goroutine 68 [running]:
github.com/terraform-providers/terraform-provider-ncloud/ncloud.convertClassicServerInstance(0xc0004c6120, 0x0)
        github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_server.go:754 +0x300
github.com/terraform-providers/terraform-provider-ncloud/ncloud.getClassicServerInstance(0xc000116900, 0xc000187544, 0x7, 0xc000215288, 0xc0005986a4, 0xc000215338)
        github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_server.go:721 +0x1b9
github.com/terraform-providers/terraform-provider-ncloud/ncloud.getServerInstance(0xc000116900, 0xc000187544, 0x7, 0x126369d27c9c2, 0xc000681ef0, 0xc00058d140)
        github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_server.go:695 +0x8e
github.com/terraform-providers/terraform-provider-ncloud/ncloud.waitStateNcloudServerForCreation.func1(0xc0005986e0, 0xc0005986a0, 0x0, 0x0, 0x2, 0x1)
        github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_server.go:503 +0x45
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc00058d020, 0xc000587880, 0xc000049020, 0xc0003b14c0, 0xc0001876d8, 0xc0001876d0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/helper/resource/state.go:110 +0x2e9
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/helper/resource/state.go:83 +0x1c6

Error: The terraform-provider-ncloud_v2.1.2 plugin crashed!
```
### Expected Behavior

Two instances will be created.
### Actual Behavior

Two instances were created. but the .tfstate file was not updated.
which means that resources on the .tfstate file is empty.
and I got the error log above.

ps. When I put the internet_line_type  = "PUBLC" on configuration of resource "ncloud_server", I got same error.
### Steps to Reproduce

1. `terraform apply`

**Comment by sangkyu-kim** [comment]
@lsh23 Thanks for bug reporting.
This issue has resolved by `v2.1.3` version 
Please use v2.1.3 version using `terraform init -upgrade`

Thanks
