### ISSUE TITLE
Error when importing SES Cluster resource

### ISSUE THREAD

**Issue by ur2e** [NaverCloudPlatform/terraform-provider-ncloud#327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : 1.5.4
Ncloud Provider version : 2.3.18
```

### Affected Resource(s)

* ncloud_ses_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ncloud_ses_cluster" "my_ses_cluster" {
}
```

### Debug Output

```
ncloud_ses_cluster.my_cluster: Importing from ID "18620754"...
ncloud_ses_cluster.my_cluster: Import prepared!
  Prepared ncloud_ses_cluster for import
ncloud_ses_cluster.my_cluster: Refreshing state... [id=18620754]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource
│ call. The plugin logs may contain more details.
╵
```

### Panic Output

```
Stack trace from the terraform-provider-ncloud_v2.3.18 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 83 [running]:
github.com/terraform-providers/terraform-provider-ncloud/ncloud.resourceNcloudSESClusterRead({0x103027028, 0x14000300c60}, 0x14000890d00, {0x102e7d960?, 0x14000886f80})
	github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_ses_cluster.go:347 +0x18b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000598700, {0x103027060, 0x14000699110}, 0xd?, {0x102e7d960, 0x14000886f80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000598700, {0x103027060, 0x14000699110}, 0x14000897ad0, {0x102e7d960, 0x14000886f80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x140001af998, {0x103027060?, 0x14000698ff0?}, 0x14000886a80)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140004f4fa0, {0x103027060?, 0x14000698810?}, 0x14000300960)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x102fe17c0?, 0x140004f4fa0}, {0x103027060, 0x14000698810}, 0x1400088c540, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140005cc1e0, {0x10302ab00, 0x14000565860}, 0x14000889b00, 0x1400056f0e0, 0x103590090, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x140005cc1e0, {0x10302ab00, 0x14000565860}, 0x14000889b00, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x290

Error: The terraform-provider-ncloud_v2.3.18 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. Identify the resource to be imported.
```hcl
resource "ncloud_ses_cluster" "my_ses_cluster" {
}
```

2. Construct the import statement 
 `terraform import ncloud_ses_cluster.my_ses_cluster {ses_cluster_id}`

**Comment by ur2e** [comment]
same issue with 
terraform version : v1.5.4 /  Ncloud Provider version v2.3.17
terraform version : v1.5.3 / Ncloud Provider version v2.3.17
terraform version : v1.5.3 / Ncloud Provider version v2.3.18
