### ISSUE TITLE
Error when importing sourcecommit repository resource

### ISSUE THREAD

**Issue by ziwooda** [NaverCloudPlatform/terraform-provider-ncloud#353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Ncloud Provider Version

```text
Terraform version : 1.5.5
Ncloud Provider version : 2.3.18
```

### Affected Resource(s)

* ncloud_sourcecommit_repository

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "ncloud_sourcecommit_repository" "my_sourcecommit_repository" {
}
```

### Debug Output

```
ncloud_sourcecommit_repository.my_sourcecommit_repository: Importing from ID "ossca-repo"...
ncloud_sourcecommit_repository.my_sourcecommit_repository: Import prepared!
  Prepared ncloud_sourcecommit_repository for import
ncloud_sourcecommit_repository.my_sourcecommit_repository: Refreshing state... [id=ossca-repo]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
```

### Panic Output
```
Stack trace from the terraform-provider-ncloud_v2.3.18 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104da58b4]

goroutine 11 [running]:
github.com/terraform-providers/terraform-provider-ncloud/ncloud.resourceNcloudSourceCommitRepositoryRead({0x10516b028, 0x1400060c540}, 0x140006c2600, {0x104fc1960?, 0x14000324f80})
	github.com/terraform-providers/terraform-provider-ncloud/ncloud/resource_ncloud_sourcecommit_repository.go:148 +0x304
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000538000, {0x10516b060, 0x14000737a70}, 0xd?, {0x104fc1960, 0x14000324f80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0xe8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000538000, {0x10516b060, 0x14000737a70}, 0x140006a4b60, {0x104fc1960, 0x14000324f80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x468
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000013878, {0x10516b060?, 0x14000737950?}, 0x14000746680)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x400
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140004f2140, {0x10516b060?, 0x14000737170?}, 0x1400060c240)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1051257c0?, 0x140004f2140}, {0x10516b060, 0x14000737170}, 0x140007d6000, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x140000a4000, {0x10516eb00, 0x14000296b60}, 0x14000881d40, 0x14000281230, 0x1056d4090, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x140000a4000, {0x10516eb00, 0x14000296b60}, 0x14000881d40, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x290

Error: The terraform-provider-ncloud_v2.3.18 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Steps to Reproduce

1. identify the resource to be imported
```hcl
resource "ncloud_sourcecommit_repository" "my_sourcecommit_repository" {
}
```

2. construct the import statement with the command below:
```
terraform import ncloud_sourcecommit_repository.my_sourcecommit_repository {repo_name}
```

**Comment by wonchulee** [comment]
@ziwooda, 
현재 sourcecommit_repository 리소스 importer 구현이 ID를 기준으로 되어있지만, 콘솔을 통해 해당 리소스의 ID정보를 확인하기 어려운 문제가 있습니다. sourcecommit_repository 의 importer 구현을 name을 기준으로 사용할 수 있게끔 변경 해주시면 좋겠습니다!
